# Generated by Django 6.0.4 on 2026-05-19 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('idconcepto', models.AutoField(db_column='idConcepto', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Concepto de Pago',
                'verbose_name_plural': 'Conceptos Arancelarios',
                'db_table': 'Concepto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('idpago', models.AutoField(db_column='idPago', primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estatus', models.CharField(default='pendiente', max_length=20)),
                ('folio', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'verbose_name': 'Transacción / Recibo',
                'verbose_name_plural': 'Historial de Pagos Recibidos',
                'db_table': 'Pago',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CargoAlumno',
            fields=[
                ('idcargo', models.AutoField(db_column='idCargo', primary_key=True, serialize=False)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('estatus', models.CharField(default='pendiente', max_length=20)),
                ('idalumno', models.ForeignKey(db_column='idAlumno', on_delete=django.db.models.deletion.CASCADE, to='Usuarios.alumno')),
                ('idconcepto', models.ForeignKey(db_column='idConcepto', on_delete=django.db.models.deletion.PROTECT, to='Finanzas.concepto')),
                ('idpago', models.ForeignKey(blank=True, db_column='idPago', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Finanzas.pago')),
            ],
            options={
                'verbose_name': 'Cargo a Estudiante',
                'verbose_name_plural': 'Estados de Cuenta (Cargos)',
                'db_table': 'Cargo_Alumno',
                'managed': True,
            },
        ),
    ]
