# Generated by Django 6.0.4 on 2026-05-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CargoAlumno',
            fields=[
                ('idcargo', models.AutoField(db_column='idCargo', primary_key=True, serialize=False)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('estatus', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'Cargo_Alumno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('idconcepto', models.AutoField(db_column='idConcepto', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'Concepto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('idpago', models.AutoField(db_column='idPago', primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estatus', models.CharField(blank=True, max_length=10, null=True)),
                ('folio', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'Pago',
                'managed': False,
            },
        ),
    ]
