# Generated by Django 6.0.4 on 2026-05-19 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('idlibro', models.AutoField(db_column='idLibro', primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('autor', models.CharField(blank=True, max_length=100, null=True)),
                ('isbn', models.CharField(blank=True, max_length=13, null=True)),
                ('editorial', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Libro (Título)',
                'verbose_name_plural': 'Catálogo de Libros',
                'db_table': 'libro',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LibroFisico',
            fields=[
                ('idlibrofisico', models.AutoField(db_column='idLibroFisico', primary_key=True, serialize=False)),
                ('codigo_barras', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(default='disponible', max_length=15)),
                ('idlibro', models.ForeignKey(db_column='idLibro', on_delete=django.db.models.deletion.CASCADE, to='Biblioteca.libro')),
            ],
            options={
                'verbose_name': 'Ejemplar Físico',
                'verbose_name_plural': 'Inventario de Ejemplares Físicos',
                'db_table': 'libro_fisico',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('idprestamo', models.AutoField(db_column='idPrestamo', primary_key=True, serialize=False)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True)),
                ('estatus', models.CharField(default='activo', max_length=15)),
                ('idalumno', models.ForeignKey(db_column='idAlumno', on_delete=django.db.models.deletion.CASCADE, to='Usuarios.alumno')),
                ('idlibrofisico', models.ForeignKey(db_column='idLibroFisico', on_delete=django.db.models.deletion.PROTECT, to='Biblioteca.librofisico')),
            ],
            options={
                'verbose_name': 'Préstamo de Libro',
                'verbose_name_plural': 'Control de Préstamos',
                'db_table': 'prestamo',
                'managed': True,
            },
        ),
    ]
