# Generated by Django 6.0.4 on 2026-05-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('idlibro', models.AutoField(db_column='idLibro', primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('autor', models.CharField(blank=True, max_length=100, null=True)),
                ('isbn', models.CharField(blank=True, max_length=13, null=True)),
                ('editorial', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Libro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LibroFisico',
            fields=[
                ('idlibrofisico', models.AutoField(db_column='idLibroFisico', primary_key=True, serialize=False)),
                ('codigo_barras', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'Libro_Fisico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('idprestamo', models.AutoField(db_column='idPrestamo', primary_key=True, serialize=False)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True)),
                ('estatus', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'Prestamo',
                'managed': False,
            },
        ),
    ]
