# Generated by Django 6.0.4 on 2026-05-19 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('rol', models.CharField(default='alumno', max_length=15)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Credenciales de Usuarios',
                'db_table': 'usuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('idalumno', models.AutoField(db_column='idAlumno', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('apellido_paterno', models.CharField(max_length=45)),
                ('matricula', models.CharField(max_length=45, unique=True)),
                ('estatus', models.CharField(default='activo', max_length=20)),
                ('idusuario', models.ForeignKey(blank=True, db_column='idUsuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Catálogo de Estudiantes',
                'db_table': 'alumno',
                'managed': True,
            },
        ),
    ]
