# Generated by Django 6.0.4 on 2026-05-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('idalumno', models.AutoField(db_column='idAlumno', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('apellido_paterno', models.CharField(max_length=45)),
                ('matricula', models.CharField(max_length=45, unique=True)),
                ('estatus', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Alumno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('rol', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Usuario',
                'managed': False,
            },
        ),
    ]
