# Generated by Django 6.0.4 on 2026-05-13 02:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CicloEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ejemplo: 2026-A', max_length=50, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estatus', models.CharField(choices=[('activo', 'Activo (Inscripciones abiertas)'), ('en_curso', 'En Curso (Clases)'), ('finalizado', 'Finalizado (Histórico)')], default='activo', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(help_text='Ej. MAT-101', max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('creditos', models.IntegerField(default=0)),
                ('semestre_ideal', models.IntegerField(default=1, help_text='Semestre en el que se sugiere cursar')),
                ('prerrequisito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materias_consecutivas', to='ControlEscolar.asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('semestre', models.IntegerField(default=1)),
                ('idciclo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ControlEscolar.cicloescolar')),
            ],
        ),
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('global', 'Todos los alumnos'), ('grupal', 'Un grupo en específico'), ('individual', 'Un alumno en específico')], default='global', max_length=20)),
                ('idalumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Usuarios.alumno')),
                ('idgrupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ControlEscolar.grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesor_asignado', models.CharField(help_text='Nombre del profesor', max_length=150)),
                ('aula', models.CharField(help_text='Ej. Edificio A - Aula 12', max_length=50)),
                ('dia', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado')], max_length=20)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('idasignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ControlEscolar.asignatura')),
                ('idgrupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ControlEscolar.grupo')),
            ],
        ),
        migrations.CreateModel(
            name='AlumnoGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('idalumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.alumno')),
                ('idgrupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ControlEscolar.grupo')),
            ],
            options={
                'unique_together': {('idalumno', 'idgrupo')},
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.CharField(choices=[('cursando', 'Cursando actualmente'), ('aprobada', 'Aprobada'), ('reprobada', 'Reprobada'), ('baja', 'Dado de Baja')], default='cursando', max_length=20)),
                ('calificacion_final', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('idalumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.alumno')),
                ('idasignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ControlEscolar.asignatura')),
                ('idciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ControlEscolar.cicloescolar')),
            ],
            options={
                'unique_together': {('idalumno', 'idasignatura', 'idciclo')},
            },
        ),
    ]
