# Generated by Django 6.0.4 on 2026-05-03 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumnoGrupo',
            fields=[
                ('idalumno', models.OneToOneField(db_column='idAlumno', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Usuarios.alumno')),
            ],
            options={
                'db_table': 'Alumno_Grupo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('idgrupo', models.AutoField(db_column='idGrupo', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'Grupo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Licenciatura',
            fields=[
                ('idlicenciatura', models.AutoField(db_column='idLicenciatura', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('abreviatura', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Licenciatura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PeriodoEscolar',
            fields=[
                ('idperiodo', models.AutoField(db_column='idPeriodo', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Periodo_Escolar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('idsemestre', models.AutoField(db_column='idSemestre', primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
            ],
            options={
                'db_table': 'Semestre',
                'managed': False,
            },
        ),
    ]
